import type { Drug } from "../../types";

/**
 * Additional commonly-dispensed medicines in Ghana, layered on top of the core
 * list in `drugs.ts` so drug search feels comprehensive rather than limited to
 * the Essential Medicines List subset.
 *
 * IMPORTANT — this is an ILLUSTRATIVE demo expansion using widely-established
 * generics, standard reference dosing, and common Ghanaian brand names. It is
 * NOT the authoritative Ghana FDA registered-products database. A complete,
 * verified dataset (Ghana FDA product list / Standard Treatment Guidelines drug
 * references) still needs to be sourced and supplied, then loaded through the
 * Admin CSV bulk-upload pipeline (see `/admin/formulary/import`). Dosing here
 * must be clinician-verified before any real-world use.
 */
export const ghanaDrugsExtended: Omit<Drug, "onEssentialMedicinesList" | "emlAlternativeDrugId">[] = [
  // --- Penicillins (share class "Penicillin" so allergy screening cross-matches) ---
  {
    id: "drug_co_amoxiclav",
    generic_name: "Amoxicillin-Clavulanate",
    brand_names: ["Augmentin", "Co-amoxiclav"],
    class: "Penicillin",
    standard_dose_range: { minMgPerDose: 375, maxMgPerDose: 1000, maxMgPerDay: 3000, frequency: "every 8-12h", weightBased: false },
    route: ["oral", "IV"],
    region_availability: ["GH"],
    contraindications: ["History of penicillin anaphylaxis", "Amoxiclav-associated jaundice/hepatic dysfunction"],
  },
  {
    id: "drug_ampicillin",
    generic_name: "Ampicillin",
    brand_names: ["Penbritin"],
    class: "Penicillin",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 1000, maxMgPerDay: 4000, frequency: "every 6h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
  },
  {
    id: "drug_cloxacillin",
    generic_name: "Cloxacillin",
    brand_names: ["Orbenin"],
    class: "Penicillin",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 2000, frequency: "every 6h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
  },
  {
    id: "drug_benzylpenicillin",
    generic_name: "Benzylpenicillin",
    brand_names: ["Crystapen", "Penicillin G"],
    class: "Penicillin",
    standard_dose_range: { minMgPerDose: 600, maxMgPerDose: 1200, maxMgPerDay: 4800, frequency: "every 6h", weightBased: false },
    route: ["IV", "IM"],
    region_availability: ["GH"],
  },

  // --- Cephalosporins (cross-reactive with penicillin allergy) ---
  {
    id: "drug_cefuroxime",
    generic_name: "Cefuroxime",
    brand_names: ["Zinnat"],
    class: "Cephalosporin",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 1000, frequency: "every 12h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
  },
  {
    id: "drug_cefixime",
    generic_name: "Cefixime",
    brand_names: ["Suprax"],
    class: "Cephalosporin",
    standard_dose_range: { minMgPerDose: 200, maxMgPerDose: 400, maxMgPerDay: 400, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_cephalexin",
    generic_name: "Cephalexin",
    brand_names: ["Keflex", "Ceporex"],
    class: "Cephalosporin",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 2000, frequency: "every 6h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },

  // --- Macrolides (share class so duplicate-therapy screening fires) ---
  {
    id: "drug_azithromycin",
    generic_name: "Azithromycin",
    brand_names: ["Zithromax", "Azithro"],
    class: "Macrolide",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 500, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_erythromycin",
    generic_name: "Erythromycin",
    brand_names: ["Erythrocin"],
    class: "Macrolide",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 2000, frequency: "every 6h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_clarithromycin",
    generic_name: "Clarithromycin",
    brand_names: ["Klaricid"],
    class: "Macrolide",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 1000, frequency: "every 12h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },

  // --- Other antimicrobials ---
  {
    id: "drug_doxycycline",
    generic_name: "Doxycycline",
    brand_names: ["Vibramycin"],
    class: "Tetracycline",
    standard_dose_range: { minMgPerDose: 100, maxMgPerDose: 100, maxMgPerDay: 200, frequency: "every 12-24h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Pregnancy", "Children under 8 years"],
  },
  {
    id: "drug_nitrofurantoin",
    generic_name: "Nitrofurantoin",
    brand_names: ["Macrodantin"],
    class: "Nitrofuran",
    standard_dose_range: { minMgPerDose: 50, maxMgPerDose: 100, maxMgPerDay: 400, frequency: "every 6h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Significant renal impairment", "Term pregnancy (38+ weeks)"],
  },
  {
    id: "drug_gentamicin",
    generic_name: "Gentamicin",
    brand_names: ["Cidomycin", "Genticyn"],
    class: "Aminoglycoside",
    standard_dose_range: { minMgPerDose: 60, maxMgPerDose: 120, maxMgPerDay: 360, frequency: "every 8h (or once daily by weight)", weightBased: true, pediatric: { mgPerKgPerDose: 2.5, maxMgPerDose: 120 } },
    route: ["IV", "IM"],
    region_availability: ["GH"],
    contraindications: ["Pre-existing renal impairment (relative)", "Myasthenia gravis"],
  },
  {
    id: "drug_levofloxacin",
    generic_name: "Levofloxacin",
    brand_names: ["Tavanic", "Levoflox"],
    class: "Fluoroquinolone",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 750, maxMgPerDay: 750, frequency: "once daily", weightBased: false },
    route: ["oral", "IV"],
    region_availability: ["GH"],
  },
  {
    id: "drug_fluconazole",
    generic_name: "Fluconazole",
    brand_names: ["Diflucan"],
    class: "Azole Antifungal",
    standard_dose_range: { minMgPerDose: 50, maxMgPerDose: 200, maxMgPerDay: 400, frequency: "once daily", weightBased: false },
    route: ["oral", "IV"],
    region_availability: ["GH"],
  },
  {
    id: "drug_aciclovir",
    generic_name: "Aciclovir",
    brand_names: ["Zovirax"],
    class: "Antiviral",
    standard_dose_range: { minMgPerDose: 200, maxMgPerDose: 800, maxMgPerDay: 4000, frequency: "5 times daily", weightBased: false },
    route: ["oral", "IV"],
    region_availability: ["GH"],
  },

  // --- Analgesics ---
  {
    id: "drug_naproxen",
    generic_name: "Naproxen",
    brand_names: ["Naprosyn"],
    class: "NSAID",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 1000, frequency: "every 12h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Active peptic ulcer", "Severe heart failure", "Third-trimester pregnancy"],
  },
  {
    id: "drug_tramadol",
    generic_name: "Tramadol",
    brand_names: ["Tramal"],
    class: "Opioid Analgesic",
    standard_dose_range: { minMgPerDose: 50, maxMgPerDose: 100, maxMgPerDay: 400, frequency: "every 6h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
    contraindications: ["Uncontrolled epilepsy", "Concurrent MAO inhibitors"],
  },
  {
    id: "drug_morphine",
    generic_name: "Morphine",
    brand_names: ["Oramorph", "MST"],
    class: "Opioid Analgesic",
    standard_dose_range: { minMgPerDose: 5, maxMgPerDose: 20, maxMgPerDay: 120, frequency: "every 4h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
    contraindications: ["Respiratory depression", "Acute severe asthma", "Paralytic ileus"],
  },

  // --- Cardiovascular ---
  {
    id: "drug_lisinopril",
    generic_name: "Lisinopril",
    brand_names: ["Zestril"],
    class: "ACE Inhibitor",
    standard_dose_range: { minMgPerDose: 5, maxMgPerDose: 20, maxMgPerDay: 40, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Pregnancy", "History of ACE-inhibitor angioedema", "Bilateral renal artery stenosis"],
  },
  {
    id: "drug_enalapril",
    generic_name: "Enalapril",
    brand_names: ["Renitec"],
    class: "ACE Inhibitor",
    standard_dose_range: { minMgPerDose: 5, maxMgPerDose: 20, maxMgPerDay: 40, frequency: "once or twice daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Pregnancy", "History of ACE-inhibitor angioedema"],
  },
  {
    id: "drug_atenolol",
    generic_name: "Atenolol",
    brand_names: ["Tenormin"],
    class: "Beta Blocker",
    standard_dose_range: { minMgPerDose: 25, maxMgPerDose: 100, maxMgPerDay: 100, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Asthma", "Second/third-degree heart block", "Severe bradycardia"],
  },
  {
    id: "drug_bisoprolol",
    generic_name: "Bisoprolol",
    brand_names: ["Concor"],
    class: "Beta Blocker",
    standard_dose_range: { minMgPerDose: 2.5, maxMgPerDose: 10, maxMgPerDay: 10, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Asthma", "Second/third-degree heart block", "Acute decompensated heart failure"],
  },
  {
    id: "drug_nifedipine",
    generic_name: "Nifedipine",
    brand_names: ["Adalat"],
    class: "Calcium Channel Blocker",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 30, maxMgPerDay: 90, frequency: "twice or thrice daily (or SR once daily)", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_methyldopa",
    generic_name: "Methyldopa",
    brand_names: ["Aldomet"],
    class: "Centrally-acting Antihypertensive",
    standard_dose_range: { minMgPerDose: 250, maxMgPerDose: 500, maxMgPerDay: 3000, frequency: "every 8-12h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Active hepatic disease", "Depression"],
  },
  {
    id: "drug_hydrochlorothiazide",
    generic_name: "Hydrochlorothiazide",
    brand_names: ["Esidrex"],
    class: "Thiazide Diuretic",
    standard_dose_range: { minMgPerDose: 12.5, maxMgPerDose: 25, maxMgPerDay: 50, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_bendroflumethiazide",
    generic_name: "Bendroflumethiazide",
    brand_names: ["Aprinox"],
    class: "Thiazide Diuretic",
    standard_dose_range: { minMgPerDose: 2.5, maxMgPerDose: 5, maxMgPerDay: 5, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_spironolactone",
    generic_name: "Spironolactone",
    brand_names: ["Aldactone"],
    class: "Potassium-sparing Diuretic",
    standard_dose_range: { minMgPerDose: 25, maxMgPerDose: 100, maxMgPerDay: 200, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Hyperkalaemia", "Severe renal impairment", "Addison's disease"],
  },
  {
    id: "drug_digoxin",
    generic_name: "Digoxin",
    brand_names: ["Lanoxin"],
    class: "Cardiac Glycoside",
    standard_dose_range: { minMgPerDose: 0.0625, maxMgPerDose: 0.25, maxMgPerDay: 0.25, frequency: "once daily", weightBased: false },
    route: ["oral", "IV"],
    region_availability: ["GH"],
    contraindications: ["Second/third-degree heart block", "Ventricular arrhythmias"],
  },
  {
    id: "drug_atorvastatin",
    generic_name: "Atorvastatin",
    brand_names: ["Lipitor"],
    class: "Statin",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 40, maxMgPerDay: 80, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Active liver disease", "Pregnancy and breastfeeding"],
  },
  {
    id: "drug_simvastatin",
    generic_name: "Simvastatin",
    brand_names: ["Zocor"],
    class: "Statin",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 40, maxMgPerDay: 80, frequency: "once at night", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Active liver disease", "Pregnancy and breastfeeding", "Concurrent strong CYP3A4 inhibitors"],
  },

  // --- GI / antiemetics / antihistamines ---
  {
    id: "drug_metoclopramide",
    generic_name: "Metoclopramide",
    brand_names: ["Maxolon"],
    class: "Antiemetic (Prokinetic)",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 10, maxMgPerDay: 30, frequency: "every 8h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
    contraindications: ["GI obstruction or perforation", "Parkinson's disease"],
  },
  {
    id: "drug_hyoscine_butylbromide",
    generic_name: "Hyoscine Butylbromide",
    brand_names: ["Buscopan"],
    class: "Antispasmodic",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 20, maxMgPerDay: 80, frequency: "every 6h", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
  },
  {
    id: "drug_loratadine",
    generic_name: "Loratadine",
    brand_names: ["Clarityne"],
    class: "Antihistamine",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 10, maxMgPerDay: 10, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_cetirizine",
    generic_name: "Cetirizine",
    brand_names: ["Zyrtec"],
    class: "Antihistamine",
    standard_dose_range: { minMgPerDose: 5, maxMgPerDose: 10, maxMgPerDay: 10, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_dexamethasone",
    generic_name: "Dexamethasone",
    brand_names: ["Decadron"],
    class: "Corticosteroid",
    standard_dose_range: { minMgPerDose: 0.5, maxMgPerDose: 8, maxMgPerDay: 16, frequency: "once or twice daily", weightBased: false },
    route: ["oral", "IV", "IM"],
    region_availability: ["GH"],
  },

  // --- Chronic / supplements ---
  {
    id: "drug_folic_acid",
    generic_name: "Folic Acid",
    brand_names: ["Folvite"],
    class: "Vitamin Supplement",
    standard_dose_range: { minMgPerDose: 0.4, maxMgPerDose: 5, maxMgPerDay: 5, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_ferrous_sulfate",
    generic_name: "Ferrous Sulfate",
    brand_names: ["Ferrograd"],
    class: "Iron Supplement",
    standard_dose_range: { minMgPerDose: 200, maxMgPerDose: 200, maxMgPerDay: 600, frequency: "once to thrice daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_levothyroxine",
    generic_name: "Levothyroxine",
    brand_names: ["Eltroxin"],
    class: "Thyroid Hormone",
    standard_dose_range: { minMgPerDose: 0.05, maxMgPerDose: 0.15, maxMgPerDay: 0.2, frequency: "once daily", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
  },
  {
    id: "drug_carbamazepine",
    generic_name: "Carbamazepine",
    brand_names: ["Tegretol"],
    class: "Anticonvulsant",
    standard_dose_range: { minMgPerDose: 100, maxMgPerDose: 400, maxMgPerDay: 1600, frequency: "every 8-12h", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["AV conduction abnormalities", "History of bone marrow depression"],
  },
  {
    id: "drug_amitriptyline",
    generic_name: "Amitriptyline",
    brand_names: ["Amitrip"],
    class: "Tricyclic Antidepressant",
    standard_dose_range: { minMgPerDose: 10, maxMgPerDose: 75, maxMgPerDay: 150, frequency: "once at night", weightBased: false },
    route: ["oral"],
    region_availability: ["GH"],
    contraindications: ["Recent myocardial infarction", "Arrhythmias", "Concurrent MAO inhibitors"],
  },
];
